runtime: nodejs14 # Ensure this matches the Node.js version you're using
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic  # App Engine adjusts automatically

handlers:
- url: /.*
  script: auto
